version: 0.2

phases:
  pre_build:
    commands:
      - make clean
  build:
    commands:
      - make
  post_build:
    commands:
      - echo Copying files to s3
      - aws s3 cp --recursive --acl public-read ./out s3://resume.gecko.tc/
      - echo invalidating cloudfront cache
      - aws cloudfront create-invalidation --distribution-id E2LL9ZONPEXXZ8 --paths /resume.pdf /resume.css /resume.html /index.html /
artifacts:
  files:
    - resume.*.md
    - out/resume.pdf
    - out/resume.css
    - out/resume.html
  discard-paths: yes